export enum AuthSuccessResponseCode {
    AUTH_201_ACCOUNT_CREATED_REQUIRE_VERIFY = "AUTH_201_ACCOUNT_CREATED_REQUIRE_VERIFY",
    AUTH_201_ACCOUNT_CREATED = "AUTH_201_ACCOUNT_CREATED",
    AUTH_201_EMAIL_VERIFIED = "AUTH_201_EMAIL_VERIFIED",
    AUTH_200_EMAIL_VERIFICATION_SENT = "AUTH_200_EMAIL_VERIFICATION_SENT",
}
